[editor]
text-width = 80
indent-guides = { render = false }

[editor.smart-tab]
enable = true
supersede-menu = false

[editor.soft-wrap]
max-wrap = 80

[editor.lsp]
enable = true

[keys.insert]
S-tab = "goto_next_tabstop"
